### ISSUE TITLE
mode 0666 seems too wide

### ISSUE THREAD

**Issue by setharnold** [sebastiannielsen/pdns-certbot#1]
Hello, I noticed a `chmod` to mode `0666` in the sources:

https://github.com/sebastiannielsen/pdns-certbot/blob/bff8371a0fc01bb59916544aee2e7ddb4e81c9fc/certbot.pl#L82

Are permissions this wide really necessary?

Thanks

**Comment by sebastiannielsen** [comment]
I did this in case the actual cert update script is run as another user than the pdns part of the script, to avoid any permission errors.

The $challengepath file isn't sensitive at all. It contains the values of the challenge objects, and cannot be used to even create DNS records outside the _acme-challenge namespace.

**Comment by sebastiannielsen** [comment]
Added security check anyways that prevents any possible misuse of the file. So even with those wide permissions, you can't even cause the script to return invalid data (like corrupt DNS records or DNS records that could lead to security issues) to pdns or similiar. It can now only return any valid or invalid challenge, nothing else.

Also fixed the missing semicolon in a subsuquent commit, and also added 2 additional security checks, both limiting the length of the response to 45 characters and also limited the number of responses to the number of configured domains. This should eliminate any risks of any malicious parties writing to the $challengepath file.

**Comment by setharnold** [comment]
Cool, thanks!
